apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: y1v8yr650-java-quarkus-gitops
  description: This is GitOps manifest for y1v8yr650-java-quarkus   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=y1v8yr650-java-quarkus
    backstage.io/kubernetes-id: y1v8yr650-java-quarkus 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: y1v8yr650-java-quarkus-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:y1v8yr650-java-quarkus
